version: '3.11'
services:
  streamlit:
    build: docker/streamlit
    image: tgaufa/ml_process_streamlit
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8501:8501
    volumes:
      - ./:/home/
  api: 
    build: docker/api
    image: tgaufa/ml_process_api
    container_name: api_backend
    ports:
      - 8080:8080
    volumes:
      - ./:/home/
