# Path Related
raw_dataset_dir: 'data/raw/Daftar Saham.xlsx'
raw_dataset_path: data/processed/raw_dataset.pkl

# Debug Related
print_debug: true

# Columns by data type related
datetime_columns:
- Date
float_columns:
- dataset.columns[1:]

# Predictors and Target Related
target: BMRI.JK
predictors: All columns except target

# Range of Data Related
range_date:
- 2020-01-01
- Today()

# ticker related data
ticker_ext: .JK
start_date: !!str 2020-01-01
end_date: date.today()
interval_date: 1d

range_other_columns:
- -1.0
- 1.0

# Replacement for missing value related
